#COOLDOWN_TIME = 360
COOLDOWN_TIME = 0 #debug
MAX_LENGTH = 60
MAX_EPISODES_PER_PODCAST = 5
MAX_PODCASTS = 10
#MAX_PODCASTS = 1 #debug
MAX_FAIL_PODCASTS = 8
LIST_SYMBOL = '#'
GPODDER_DB_PATH = "/gPodder/Database"
GPODDER_NOTIFIER_PATH = "/home/frontier/Proyectos/gpodder-notifier/" # development path
#GPODDER_NOTIFIER_PATH = /usr/lib/python3/dist-packages # release path
GPODDER_NOTIFIER_USER_PATH = "/.gpodder-notifier/"
GPODDER_NOTIFIER_DAT_NAME = "gpodder-notifier.dat"
